name: DAST - ZAP Baseline (Juice Shop)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    services:
      juice_shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl -fsS http://localhost:3000 || exit 1"
          --health-interval=10s --health-retries=12 --health-timeout=5s

    steps:
      - uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://juice_shop:3000'
          format: 'long'
          cmd_options: '-d'
          fail_action: true
          report: 'zap_baseline.html'

      # Always upload, even if the scan step fails
      - name: Upload ZAP HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap_baseline.html
          if-no-files-found: warn

      # (Optional) capture the full workflow logs as an artifact too
      - name: Upload runner logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: runner-logs
          path: ${{ github.workspace }}/**/*.log
          if-no-files-found: ignore
