name: DAST - ZAP Baseline (Juice Shop)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap:
    runs-on: ubuntu-latest

    services:
      juice_shop:
        image: bkimminich/juice-shop
        ports:
          - 3000:3000
        # NOTE: removed health-cmd because the image doesn't have curl/wget

    steps:
      - uses: actions/checkout@v4

      - name: Wait for Juice Shop (retry)
        run: |
          for i in {1..60}; do
            if curl -fsS http://localhost:3000 >/dev/null; then
              echo "Juice Shop is up";
              exit 0;
            fi
            echo "Waiting for Juice Shop... ($i/60)";
            sleep 5;
          done
          echo "Juice Shop did not become ready in time";
          exit 1

      - name: ZAP Baseline Scan
        id: zap
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://localhost:3000'
          format: 'long'
          cmd_options: '-d'
          fail_action: true
          report: 'zap_baseline.html'

      - name: Upload ZAP HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: zap-baseline-report
          path: zap_baseline.html
          if-no-files-found: warn
