name: Security Gates (PR)

on:
  pull_request:
    branches: [ "main" ]

jobs:
  gates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install semgrep
          sudo apt-get update
          sudo apt-get install -y trivy

      # Semgrep gate: fail if any ERROR-level finding is present
      - name: Semgrep (gate)
        run: semgrep --config .semgrep.yml --severity ERROR --error

      # Trivy filesystem gate: fail on High/Critical
      - name: Trivy FS gate
        run: trivy fs --severity CRITICAL,HIGH --exit-code 1 .

      # Optional: Gitleaks gate (action already fails on findings)
      - name: Gitleaks (gate)
        uses: gitleaks/gitleaks-action@v2
        with:
          fail: true
          report-format: json
